apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "akscluster"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "akscluster"
    spec:
      containers:
        - name: "akscluster"
          image: "mgronbaraksregistry.azurecr.io/akscluster"
          ports:
          - containerPort: 80
          env:
            - name: REACT_APP_API_ENPOINT
              valueFrom:
                configMapKeyRef:
                  name: ruuvi-configmaps
                  key: api.endpoint
            - name: REACT_APP_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: ruuvi-configmaps
                  key: api.key